### ISSUE TITLE
Changing OSC buffer size to 4095 while running causes run to hang.

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#2]
Steps to reproduce:
Start a run with OSC1 enabled (other settings shouldn't, nor does wifi or agent).  While running update the OSC1 Samples to 4095.

OpenScope returns :
{"osc":{"1":[{"command":"setParameters","statusCode":2684354570,"wait":0}]}}

Run stops but run button remains 'STOP' rather than reverting to run.

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/fc57a1d9a31de7276c965f068d60519a6592978d
