### ISSUE TITLE
Select firmware drop down sorts incorrectly.

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#20]
Looks like major version may be ignored.
Also check to make sure we're using numeric sorting not alphabetic sorting.

![image](https://user-images.githubusercontent.com/1994983/26992485-baa54016-4d13-11e7-8773-60c375d8d060.png)

**Comment by SudharsanSukumar** [comment]
Fixed in #1c4a62b8088b5813bf3e66d78866616391eafc92. See Digilent/dip-angular2#3646c9bcf55ec231b0c2a9e169171267604672de
