### ISSUE TITLE
Add device MAC address to device enumeration and display in device config panel

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#22]
We currently do not report the mac address in WaveForms Live.  We should add the device mac address(es) to the enumeration and display the mac address for each NIC on the WFL config page.

Work around:
OpenScope MZ currently prints it's mac address to the serial terminal (at 1.25 Mbaud) at boot.

**Comment by SudharsanSukumar** [comment]
Added in https://github.com/Digilent/waveforms-live/commit/a912180d643201899d73f3b790784aba0e5145c0.
