### ISSUE TITLE
Update config menu to allow user to add agent even if unable to communicate with device.

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#23]
If a user needs to recover from corrupt firmware they may need to add the agent to WFL even though the agent can't communicate with the device (because it DNE or is in bootloader mode).  Update the config menu to allow users a way to recover in this scenario.

Reported in 1.0.5

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/6d9a2ba27e1333cd929b5cd05c58efc576d81f06.
