### ISSUE TITLE
Firmware fetch timeout

### ISSUE THREAD

**Issue by SudharsanSukumar** [Digilent/waveforms-live#24]
For people with slow connections, downloading the firmware may cause a timeout and display an error. 

Workaround:
Click the button multiple times until it works. This causes the browser to cache the chunks of the file it receives until the whole file is transferred and cached.

**Comment by samkristoff** [comment]
Reported in 1.0.5

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/6d9a2ba27e1333cd929b5cd05c58efc576d81f06.
