### ISSUE TITLE
Removing an Agent from the device manager does not release the device.

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#25]
When a user removes an agent card form the WFL device manager the agent is removed without releasing the device.  

Update to release any active device before removing the agent.

Reported in 1.0.5

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/6d9a2ba27e1333cd929b5cd05c58efc576d81f06.
