### ISSUE TITLE
Calibration menu should warn users to save data before exiting

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#26]
After a successful calibration the user must save the calibration data to flash or sd for the values to persist beyond device reboot.  It is easy for a user to miss this and simply click done.

Add a warning dialog if the user clicks done but has not saved the calibration data.

Reported in 1.0.5

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/6923c91afc7bc3402b10bf56179ad1e070bee925.
