### ISSUE TITLE
Failed to start master/v1.0.6

### ISSUE THREAD

**Issue by teon** [Digilent/waveforms-live#28]
I'm trying to setup waveforms live on my Ubuntu 16.04. Did everything acording to instruction (node version check, npm check, installed ionic and cordova, then npm install - all fine).
When I start:

```
x:{/opt/waveforms-live}$ ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

> waveforms-live@1.0.6 ionic:serve /opt/waveforms-live
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

[19:00:58]  ionic-app-scripts 1.0.0 
[19:00:58]  watch started ... 
[19:00:58]  build dev started ... 
[19:00:58]  clean started ... 
[19:00:58]  clean finished in 4 ms 
[19:00:58]  copy started ... 
[19:00:58]  transpile started ... 
[19:01:02]  typescript: src/components/chart/chart.component.ts, line: 1401 
            Property 'rawData' does not exist on type 'LaInstrumentService'. 

    L1400:  else if (data.option === 'Export Binary') {
    L1401:  ta', this.deviceManagerService.devices[this.deviceManagerService.activeDeviceIndex].instruments.la.rawData);

[19:01:02]  transpile failed 
[19:01:02]  dev server running: http://localhost:8100/ 

[19:01:02]  copy finished in 4.41 s 
[19:01:02]  watch ready in 4.48 s 
```
And when accessing browser - the same error on web.
Don't know why it says I need to install cordova (i did npm install -g cordova at least 3 times to get rid of the message), and dont know why theres the error. Please help.

**Comment by SudharsanSukumar** [comment]
The cordova warning is a bug in that version of the Ionic CLI. In package.json, remove the caret in front of the dip-angular2 version. It should just read "dip-angular2": "0.7.4". Next, delete your node_modules and npm install again.

Let me know if that works,
Dharsan

**Comment by SudharsanSukumar** [comment]
The cordova warning message is just a bug in that version of the Ionic CLI. 

Just comment out line 1401 in src/components/chart/chart.component.ts for now. We were in the middle of exporting raw binary data from the OpenScope and for some reason both myself and the transpiler didn't seem to catch this when we built 1.0.6.

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/f078b38a1e415018b3e35887aa10178763ce6be1.

**Comment by teon** [comment]
Confirmed, in v1.0.7 everything works! thank you!
