### ISSUE TITLE
Add tool tips to buttons in FFT button column

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#34]
Most buttons in WFL have tooltips, but buttons between the chart and the control panel (FFT, Bode, Zoom, etc) do not have tooltips.

Add appropriate tooltips to all buttons.

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/c6f9a93c2a96715b0574334f9ec781d94299e016
