### ISSUE TITLE
Add black background behind exported PNG

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#36]
When exporting a PNG there is a transparent section at the bottom that should be black.

![image](https://user-images.githubusercontent.com/1994983/28592037-a74465c2-713c-11e7-961c-91061b7d10fb.png)

**Comment by SudharsanSukumar** [comment]
Fixed in https://github.com/Digilent/waveforms-live/commit/c6f9a93c2a96715b0574334f9ec781d94299e016
