### ISSUE TITLE
Dual channels wavegen

### ISSUE THREAD

**Issue by sanpii** [Digilent/waveforms-live#38]
My first real bug 😃 

With a dual channel instrument, the two panel are sync: when I change the configuration on the first panel, the second also changes.

**Comment by PhantomMachine** [comment]
Devices with multiple AWG channels should now be handled properly. The state for each individual channel is now handled inside the function generator component. Editing the configuration of one channel shouldn't change the configuration of another channel, and the channels can be independently turned off/on.

commit: b043ec7b3367c79bce222951fab63060fed9e00a

**Comment by sanpii** [comment]
Thank you!
