### ISSUE TITLE
Adding second math function causes bottom bar to vertically expand slightly.

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#4]
- Add a simulated device.
- Click single.
- Click math and choose a math function.  Notice the bottom bar (containing the math button) remains the same height.
- Click math and choose a second math function.  Notice the bottom bar vertically expands slightly.

**Comment by PhantomMachine** [comment]
Resolved by fixing the height of the bottom bar to the height it assumes with the addition of the second math function.

commit: 916a174f1597d025c25729290ff85bee9b7f3ece
