### ISSUE TITLE
Add meaning of LEDs to Wiki or manual

### ISSUE THREAD

**Issue by EmbeddedMan** [Digilent/waveforms-live#42]
Maybe I just didn't search through the documentation enough, but I tried and couldn't find a table that listed all of the possible LED states and what they mean. It would be handy to provide this information.

**Comment by EmbeddedMan** [comment]
OK, I found a list of LED meanings here : https://reference.digilentinc.com/reference/instrumentation/openscope-mz/reference-manual but it doesn't show the LED pattern I'm seeing on my Open Scope (see issue #41)

**Comment by SudharsanSukumar** [comment]
At the very bottom of the reference manual under "Troubleshooting - LED Indicators" it says what the LEDs mean and explains how the last octet of the IP address is encoded with the 3 LEDs. In your case, you mention green blinking 7 times by itself and then all three blinking once. I believe the order may be:

All three blink once and then green continues another 7 times. 

This would correspond to an IP address of xxx.xxx.xxx.118. The bug mentioned in issue #41 still actually connects the OpenScope to the network which explains why the blue LED is solid on and the other three are blinking your the last octet of your IP.

I agree that finding that information should be a little easier. We'll post here if we make a change to the documentation.

**Comment by EmbeddedMan** [comment]
Ahhh! That makes complete sense. OK, so you can close this issue then - I just didn't understand exactly what was meant in that list of LED codes. Makes sense now.
