### ISSUE TITLE
Calibration save location popover looks broken

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#43]
After successfully calibrating the device the user is prompted to select a location to save the calibration data.  This used to use a drop-down popover but since it is in a modal this did not work correctly on firefox.  

The current solution works on all supported browsers but if the user clicks on or to the right of the down arrow inside the select box the options popover is rendered with its upper left corner on the down arrow icon and overlaps the UI elements to the right of the select.  This is still completely functional but looks unintentional / broken.

Consider revamping the UI to prevent this from looking broken.

**Comment by PhantomMachine** [comment]
In Chrome, the browser captures the arrow element in the on click event whereas other browsers capture the containing div. The captured element is used to position the dropdown, so in Chrome the dropdown is improperly positioned when the user clicks on the arrow.

To fix the issue of the dropdown covering other UI elements, a redesign of the success slide in the calibration component was done. Now, the save location select, calibration results and the option to apply calibration on boot reside within an Advanced options expander. When expanded, clicking on the arrow will still cause the select to use the arrow for positioning (in Chrome) but won't cover the Done button.

commit: e6f617d
