### ISSUE TITLE
Reset and Reinitialize does not clear active WFL buffer.

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#52]
When you click the Reset and Reinitialize button in WaveForms Live the device and settings are reset but any data in the buffer in WaveForms Live will remain visible.  We should clear the WFL buffer when the user resets the device through WFL.

**Comment by PhantomMachine** [comment]
Made additions to the resetDevice method to clear the device buffer and then redraw the graph once done.

commit: 8e184c5a6da064a291982212232f24bfd62b01da
