### ISSUE TITLE
Add link to dlog parser where appropriate in WFL

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#54]
Add link(s) in WFL to point user to [dlog-utils](https://github.com/Digilent/dlog-utils).

Error message when user tries to retrieve a large log.
Error message when user tries to convert a large log from the HDD.
etc

**Comment by PhantomMachine** [comment]
The More Info links now redirect to the WFL wiki faq, where some new entries have been created regarding the transfer and conversion of >10MB log files. The transfer faq explains how to transfer a large file from the SD card, and provides a link to dlog-utils for conversion once transferring has been completed. The conversion faq has a link to the dlog-utils explaining that it is used for converting dlogs to csv files.

Also, when trying to convert a local log file in WFL that is >10MB, the error message that pops up now explains that dlog-utils are necessary for conversion, and provides a link to the dlog-utils repository.

commit: c208bd8746e909eae793886a2ddfdef1a2032c59
