### ISSUE TITLE
Cannot start acquisition after using logger

### ISSUE THREAD

**Issue by SudharsanSukumar** [Digilent/waveforms-live#55]
Using oscilloscope then logger then oscilloscope causes error because parameters are the same but WFL hasn't reset previous run values.

**Comment by PhantomMachine** [comment]
When entering the logger page from the instrument-panel-chart, an onLoggerDismiss option is passed in the navCtrl.push call. This option is a function and emits a resetDevice event. Previously, this wasn't being called inside the logger component when exiting the logger. Adding the function call to the onLoggerDismiss option eliminated this bug.

commit: 46965a5df5e8e0e352037f620f5d3affbf1c9b92
