### ISSUE TITLE
Add ability select local .hex when recovering corrupt OpenScope MZ

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#56]
When recovering corrupt firmware as described [here](https://reference.digilentinc.com/reference/instrumentation/openscope-mz/recover-from-corrupt-firmware) if a user selects OpenScope MZ they do not have the option to select a .hex file from their local machine.  This could be an issue if the user does not have a (decent) internet connection.  

Add ability to browse for firmware after selecting OpenScope MZ.

Work around:
Select Other and browse for a local .hex file.
or
Go into the settings page and increase the timeout to something large enough for the firmware download to complete, then follow the standard recovery directions.

**Comment by PhantomMachine** [comment]
When uploading firmware, if OpenScope MZ is selected for device, the user can now select 'Latest' or 'Other' from a drop down. Selecting Latest preserves the original firmware flashing flow, where WFL downloads the latest firmware version to the desktop and transfers that to the agent. Selecting Other causes a browse button to appear in the modal. Hitting browse opens a file browser where the user is directed to select a hex file. Once submitted, WFL will transfer the selected firmware hex to the agent for flashing.

commit: 88a568decd3f7bf8b9c5562da102f96e5cb7bc7f
