### ISSUE TITLE
Differentiate between firmware upload failures

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#57]
When uploading firmware there are several potential failures:

Firmware file does not download correctly
Firmware file is not transfered to the agent successfully
Firmware is not programmed correctly.
etc

Currently the error reported to the user provides no information on which stage failed.  Update the error handler to differentiate between the potential failures and provide a more meaningful error message.

**Comment by PhantomMachine** [comment]
Identified the stages where an error can occur and what the error looks like. Created firmwareTransmissionError, firmwareDownloadError and firmwareProgrammingError definitons in the wflDictionary, each with a message that gives an idea of which stage the error occurred at.
