### ISSUE TITLE
Add 'Fork me on github' ribbon to WFL

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#58]
Add 'Fork me on github' ribbon to WFL

**Comment by PhantomMachine** [comment]
On desktop, a Form Me ribbon will appear in the upper right corner of the page. For mobile, the ribbon was intrusive was drawn on top of some of the ui elements, and so a button was used instead. Clicking the button or the ribbon opens the WFL repo in a new tab.

commit: 6d577691a18a9590a88911e814de972446539b30
