### ISSUE TITLE
Update calibration UI

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#61]
Add details about why calibration is necessary / what is happening
Add wire connection image  (see #3)
Collapse section that displays calibration constants (let user expand if they want to see it)
Collapse section that provides save location options (advanced users can expand to save to SD)
Reduce 'save', 'ok', 'cancel' buttons to save / cancel.

**Comment by PhantomMachine** [comment]
Added short cursory blurb about why calibration is necessary, which includes a link to the FAQ for more information.

commit: f434bf8930be9af9e1b16d722b19bdea90c5bcbc

Added wire connection image

commit: 3ba2c8d47d945f824ea4cea3ed75488a9faf71e4

Moved the calibration constants and save location options underneath a collapsible section

commit: e6f617dd70eb7b89fa834e1b954fc7d1cf4cbf3b
