### ISSUE TITLE
Indicate to user that wifi will disconnect before scanning

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#72]
When the user clicks the 'Scan' button in the wifi config page the wifi radio must disconnect from the network (if connected) before performing the scan.  The radio does not reconnect to the network after the scan.

At a minimum WaveForms Live should alert the user that the hardware will disconnect from the network.   We could also try to reconnect if the user leaves the modal without establishing a new connection.

**Comment by PhantomMachine** [comment]
Added tooltip to the 'Scan' button that says the device must disconnect from the network before scanning.

commit: f434bf8930be9af9e1b16d722b19bdea90c5bcbc
