### ISSUE TITLE
the ionic grid layout not work in the project. How to use grid layout system in the project

### ISSUE THREAD

**Issue by victory460** [Digilent/waveforms-live#79]
Dear digilent!
It is a cool project,but I  find such as the following codes not work.Whiy?
`<ion-grid>
  <ion-row>
    <ion-col col-4>
      1 of 4
    </ion-col>
    <ion-col col-2>
      2 of 4
    </ion-col>
    <ion-col col-2>
      3 of 4
    </ion-col>
    <ion-col col-4>
      4 of 4
    </ion-col>
  </ion-row>
</ion-grid>`

**Comment by PhantomMachine** [comment]
Hey Victory460,

This sounds more like an issue with the Ionic side of things than an issue with WaveForms Live. I'm going to close this issue, but I want to extend a helping hand out to you.

This project is built with an older version of Ionic, and while Ionic Grid is available, its use might not be the same as what current documentation outlines. If you're trying to build with a newer version of Ionic, this might cause some issues. Try installing Ionic@2.2.2 and building with that.

If you continue to have issues, I'll see what I can do to help 1v1. Send me an email using the address on my GitHub profile and we'll work it out from there.

Let me know how things go,
Andrew
