### ISSUE TITLE
Soundcard device

### ISSUE THREAD

**Issue by Lahorde** [Digilent/waveforms-live#86]
I'm quite new to Waveforms live. I'm used to work with waveforms 2015 with AD2. 
Recently, I was looking for some PC software to use soundcard as an oscilloscope. We can find some softwares googling "soundcard oscilloscope". After some tests, these softwares aren't very good...

Waveforms live is an opensource project. After some quick tests, it's a good job. An easy, cheap and quick way to do efficient measurements / signal generation. But a thing is missing : a new device, your computer sound card! 
Is it technically possible? Can I help you?

**Comment by samkristoff** [comment]
Hey Lahorde,

We recently added the sound card as an option in WaveForms (WaveForms 'desktop' not WaveForms Live).  Grab the latest version [here](https://reference.digilentinc.com/reference/software/waveforms/waveforms-3/start ) and give it a shot!

**Comment by Lahorde** [comment]
You are my hero!!! Good job, just tested... it's perfect...
